add Vault.sol and Authorize.sol
layer-3/broker-contracts pull request #1
Opened 2024-08-01 12:49 UTC by mnaichuk

2024-08-02 07:05 UTC, mod requested changes
On my side I would:
- [ ] Switch RBAC to onlyOwner as we have only 1 role
- [ ] Avoid using enumarableMap as you don't use it
- [ ] Probably we can remove OZ fully, like copying IERC20.sol

2024-08-02 12:47 UTC, mod commented on src/TimeRangeAuthorizer.sol
> +import "@openzeppelin/contracts/access/AccessControl.sol";
use Owner RBAC if no multirole

2024-08-02 14:05 UTC, mnaichuk commented
> On my side I would:
> 
> * [x]  Switch RBAC to onlyOwner as we have only 1 role
> * [x]  Avoid using enumarableMap as you don't use it
> * [ ]  Probably we can remove OZ fully, like copying IERC20.sol

I would still keep ReentrancyGuard from OZ

2024-08-02 14:37 UTC, mod requested changes
- [ ] Comments
- [ ] Align to TimeRange naming
- [ ] Rename Vault to LiteVault

2024-08-03 10:36 UTC, mod commented on src/LiteVault.sol
> +    }
Todo, we need to add the ability to transfer Ownership,
Either we copy Ownable.sol or implement here

2024-08-03 10:37 UTC, mod approved these changes

2024-08-03 10:37 UTC, merged